# Generated by Django 4.1 on 2022-09-01 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='team_members',
            field=models.ManyToManyField(blank=True, related_name='task', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_leader',
            field=models.ForeignKey(limit_choices_to={'role': 'Team Leader'}, on_delete=django.db.models.deletion.CASCADE, related_name='team_l', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_members',
            field=models.ManyToManyField(limit_choices_to={'role': 'Team Member'}, related_name='team_m', to=settings.AUTH_USER_MODEL),
        ),
    ]
