# Generated by Django 4.1 on 2022-09-02 08:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapi', '0002_alter_task_completed_at_alter_task_team_members_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_members',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'Team Member'}, related_name='team_m', to=settings.AUTH_USER_MODEL),
        ),
    ]
